### ISSUE TITLE
Scalability problem

### ISSUE THREAD

**Issue by D063520** [AKSW/HARE#1]
Hi! 

I tried out this library. My aim was to compute the HARE scores for Wikidata. The current dump is around 250 Gb and 2 billion triples. Unfortunately I experienced that the library consumes a lot of memory and needs a lot of time. On a 500 Gb RAM machine I was not able to compute the numbers since I was running out of memory. Can you confirm these scalability issues? I guess that a 2 TB RAM machine would be needed to compute the numbers.
I saw that in the corresponding publication the experiments stopped at 100 Million triples. Is this due to a memory consumption problem?

Thank you
D063520

**Comment by RicardoUsbeck** [comment]
Hi, we will look into this problem. Did you install BLAS? 

CC: @MichaHoffmann @Kunal-Jha @gsjunior86 @abdoudesouki @ngonga

**Comment by D063520** [comment]
No, I did not install BLAS (or maybe I did without noticing). As far as I see the parser you use is very slow and you use a Hash Map to create a dictionary which eats up a lot of memory. The problem does not seams to be the matrix computations.

**Comment by MichaHoffmann** [comment]
Do you arrive at the matrix computations or does it stop at the parsing
step?

2018-01-02 13:09 GMT+01:00 Dennis Diefenbach <notifications@github.com>:

**Comment by D063520** [comment]
it stops before

**Comment by MichaHoffmann** [comment]
to store 10**8 strings in memory,  you would need about
>>> sys.getsizeof('a')*10**8/1024/1024/1024
>>>3
3 TB of ram; so for larger files one would need to work either without
strings( would not consume that much less memory ) or store everything
filebased. That would make parsing much slower.
It has been a while but i think i did it that way as a compromise up to a
reasonable size.

2018-01-02 13:14 GMT+01:00 Dennis Diefenbach <notifications@github.com>:

**Comment by MichaHoffmann** [comment]
We had an approach using an DB (sqlite) instead of a Hashmap for DBPedia
before, if i remember correctly, that could at least get you to the
computation step. Should i look it up?

2018-01-02 13:18 GMT+01:00 Michael Hoffmann <michoffmann.potsdam@gmail.com>:

**Comment by D063520** [comment]
So you confirm that in the current implementation that memory consumption is expected?

**Comment by D063520** [comment]
And you say that you could propose an implementation that would scale in memory but which would be slower in time?

**Comment by MichaHoffmann** [comment]
I can look for one; not sure if i can find it but you could write an Index
Sink with a sqlite backend anyway, if you need one. The memory consumption
sounds about right to me, using that simple calculation there.

2018-01-02 13:26 GMT+01:00 Dennis Diefenbach <notifications@github.com>:

**Comment by D063520** [comment]
Ok, I only wanted to know if I didn't make any mistake. If at some point you have an implementation that can compute the numbers for Wikidata and does not consume to many resources notify me please. Thank you D063520
